.\" Please adjust this date whenever revising the manpage.
.Dd July 3, 2012
.Dt CPARSER 1
.Sh NAME
.Nm cparser
.Nd C compiler
.Sh SYNOPSIS
.Nm
.Op Fl c | S | E | -print-ast
.Op Fl -print-implicit-cast
.Op Fl -print-parenthesis
.Op Fl ansi
.Op Fl std= Ns Ar standard
.Op Fl - Ns Oo Cm no- Oc Ns Cm gcc
.Op Fl - Ns Oo Cm no- Oc Ns Cm ms
.Op Fl g
.Op Fl O Ns Ar level
.Op Fl W Ns Oo Cm no- Oc Ns Oo Cm error= Oc Ns Ar warning
.Op Fl w
.Op Fl I Ar dir
.Op Fl L Ar dir
.Op Fl D Ns Ar macro Ns Op Ar =defn
.Op Fl U Ns Ar macro
.Op Fl f Ar option
.Op Fl finput-charset= Ns Ar encoding
.Op Fl b Ar option
.Op Fl l Ar library
.Op Fl o Ar outfile
.Op Fl x Ar language
.Op Fl Wl, Ns Ar option
.Op Fl Wp, Ns Ar option
.Ar
.Sh DESCRIPTION
.Nm
is a C compiler, which can parse C90 and C99 as well as many GCC and some MSC extensions.
It also provides many useful analyses for warnings and generates concise messages in case of error.
It uses libFIRM for optimization and code generation.
The compiler driver is largely compatible with GCC.
.Sh OPTIONS
.Bl -tag
.It Fl c
Compile the input files to object files.
The default output filename is the input filename with the extension replaced by .o.
.It Fl S
Compile the input files to assembler.
The default output filename is the input filename with the extension replaced by .s.
.It Fl E
Preprocess the input file only.
By default the result is output to stdout.
.It Fl -print-ast
Output the abstract syntax tree of the parsed input file as C again.
.It Fl -print-implicit-cast
When using
.Fl -print-ast ,
show casts, which are inserted by the semantic checks.
.It Fl -print-parenthesis
When using
.Fl -print-ast ,
show all expressions fully parenthesized.
.It Fl ansi
Same as -std=c90 (for C) or -std=c++98 (for C++).
.It Fl std= Ns Ar standard
Select the language standard.
Supported values are:
.Bl -tag -compact -width "iso9899:1990"
.It Cm c89
.It Cm c90
.It Cm iso9899:1990
ISO C90
.It Cm gnu89
ISO C90 with GCC extensions
.It Cm c99
.It Cm iso9899:1999
ISO C99
.It Cm gnu99
ISO C99 with GCC extensions
.It Cm c++98
ISO C++ 1998.
Not supported yet.
.It Cm gnu++98
ISO C++ 1998 with GCC extensions.
Not supported yet.
.El
.It Fl - Ns Oo Cm no- Oc Ns Cm gcc
Disable/enable GCC extensions.
This switch supersedes
.Fl std .
.It Fl - Ns Oo Cm no- Oc Ns Cm ms
Disable/enable MSC extensions.
.It Fl g
When compiling C files, add debug information in
.Tn stabs
format.
.It Fl O Ns Ar level
.\" TODO expand
Select the optimization level.
Sensible values are between 0 and 4, inclusive.
.\" TODO expand
.It Fl W Ns Ar warning
Enable the specified warning.
.It Fl Wno- Ns Ar warning
Disable the specified warning.
.It Fl Werror= Ns Ar warning
Enable the specified warning and turn it into an error.
.It Fl Wno-error= Ns Ar warning
Force the specified warning to only be a warning, even in the presence of
.Fl Werror .
This neither enables nor disables the warning itself.
.It Fl Waddress
Warn about suspicious use of addresses, like using the address of a function or variable as boolean condition or comparing with the address of a string literal.
.It Fl Waggregate-return
Warn about defining or calling a function, which returns a struct or union by value.
.It Fl Wall
Activate most warnings.
In particular these are
.Fl Waddress ,
.Fl Wattribute ,
.Fl Wchar-subscripts ,
.Fl Wcomment ,
.Fl Wempty-statement ,
.Fl Wformat ,
.Fl Wimplicit-function-declaration ,
.Fl Wimplicit-int ,
.Fl Winit-self ,
.Fl Wmain ,
.Fl Wnonnull ,
.Fl Wparentheses ,
.Fl Wpointer-arith ,
.Fl Wredundant-decls ,
.Fl Wreturn-type ,
.Fl Wshadow-local ,
.Fl Wsign-compare ,
.Fl Wstrict-prototypes ,
.Fl Wswitch-enum ,
.Fl Wunknown-pragmas ,
.Fl Wunreachable-code ,
.Fl Wunused-function ,
.Fl Wunused-label ,
.Fl Wunused-parameter ,
.Fl Wunused-value ,
.Fl Wunused-variable .
.It Fl Wcast-qual
Warn whenever a pointer cast removes qualifiers from the pointed-to type, e.g. casting a const char* to char*.
.It Fl Wchar-subscripts
Warn about using an expression of type char as array subscript, e.g. char\ c; arr[c].
.It Fl Wdeclaration-after-statement
Warn about mixing declarations and statements, which is not allowed prior to C99.
.It Fl Wdiv-by-zero
Warn about compile-time integer division by zero.
.It Fl Wempty-statement
Warn about empty statements, i.e. statements which only consist of a single
.Sq \&; .
Use {} as replacement to avoid this warning.
.It Fl Werror
Treat warnings as errors, i.e. do not continue after parsing when a warning is encountered.
.It Fl Wextra
(Alias
.Fl W Ns )
Activate some more warnings.
In particular these are
.Fl Wempty-statement ,
.Fl Wshadow ,
.Fl Wunused-parameter ,
.Fl Wunused-value .
.It Fl Wfatal-errors
Immediately abort compilation when encountering an error.
.It Fl Wformat
Check format strings of char and wchar_t functions.
.It Fl Wimplicit
Activate
.Fl Wimplicit-function-declaration ,
.Fl Wimplicit-int .
.It Fl Wimplicit-function-declaration
Warn about calling a function without a prior declaration.
.It Fl Wimplicit-int
Warn about declarations whose declaration specifiers do not include a type specifier.
.It Fl Winit-self
Warn about uninitialized variables which are initialized with themselves.
.It Fl Wlong-long
Warn if the type
.Sq long long
is used.
.It Fl Wmain
Warn if the type of
.Sq main
is suspicious, i.e. if it is not a non-static function declared as either int\ main(void), int\ main(int,\ char**) or, as an extension, int\ main(int,\ char**,\ char**).
.It Fl Wmissing-declarations
Warn if a non-static function or a global variable without a storage class is defined without a prior declaration.
This is typically a sign of a missing #include or that the object should be static.
.It Fl Wmissing-noreturn
Warn about functions, which are candidates for the attribute
.Sq noreturn .
.It Fl Wmissing-prototypes
Warn if a global function is defined without a previous prototype declaration.
.It Fl Wmultichar
Warn if a multicharacter constant
.Pf ( Sq FOOF )
is used.
.It Fl Wnested-externs
Warn if an
.Sq extern
declaration is encountered within a function.
.It Fl Wparentheses
Warn if parentheses are omitted in certain contexts.
Warn if an assignment is used as condition, e.g. if\ (x\ =\ 23).
Warn if && without parentheses is used within ||, e.g. if\ (x\ ||\ y\ &&\ z).
Warn if it there may be confusion which
.Sq if Ns
-statement an
.Sq else Ns
-branch belongs to, e.g. if\ (x)\ if\ (y)\ {}\ else\ {}.
Warn if cascaded comparisons appear which do not have their mathematical meaning, e.g. if\ (23\ <=\ x\ <\ 42).
Warn if + or - is used as operand of << or >>, e.g. x\ +\ y\ <<\ z.
.It Fl Wredundant-decls
Warn about redundant declarations, i.e. multiple declarations of the same object or static forward declarations which have no use before their definition.
.It Fl Wshadow
Warn when a new declaration shadows another declaration with the same name in an outer scope.
.It Fl Wshadow-local
Like
.Fl Wshadow ,
but only warn if the shadowed declaration is not global, e.g. a local variable shadows a parameter or another local variable.
.It Fl Wunreachable-code
Warn when the compiler determines that a statement (or in some cases a part thereof) will never be executed.
.It Fl Wunused
Activate
.Fl Wunused-function ,
.Fl Wunused-label ,
.Fl Wunused-parameter ,
.Fl Wunused-value ,
.Fl Wunused-variable .
.It Fl Wunused-parameter
Warn when a parameter is never used or only ever read to calculate its own new value, e.g. x\ =\ x\ +\ 1.
.It Fl Wunused-variable
Warn when a variable is never used or only ever read to calculate its own new value, e.g. x\ =\ x\ +\ 1.
.It Fl w
Suppress all warnings.
.It Fl I Ar dir
Add the directory
.Ar dir
to the paths to be searched for include files.
.It Fl L Ar dir
Add the directory
.Ar dir
to the paths to be searched for libraries.
.It Fl D Ns Ar macro
Define the preprocessor macro
.Ar macro
which will expand to 1.
.It Fl D Ns Ar macro=defn
Define the preprocessor macro
.Ar macro
and set its expanded value to
.Ar defn .
.It Fl U Ns Ar macro
Undefine the preprocessor macro
.Ar macro .
.It Fl f Ar option
Set a frontend or optimizer option.
Use
.Fl fhelp
to get a list of supported optimizer options.
.It Fl f Ns Oo Cm no- Oc Ns Cm diagnostics-show-option
Show the switch, which controls a warning, after each warning.
Default is on.
.It Fl finput-charset= Ns Ar encoding
Select the encoding of the input.
Supported values are
.Cm ISO_8859-1:1987
(aliases
.Cm CP819 ,
.Cm IBM819 ,
.Cm ISO-8859-1 ,
.Cm ISO8859-1 ,
.Cm ISO_8859-1 ,
.Cm csISOLatin1 ,
.Cm iso-ir-100 ,
.Cm l1
and
.Cm latin1 Ns
),
.Cm ISO-8859-15
(aliases
.Cm ISO8859-15 ,
.Cm ISO_8859-15
and
.Cm Latin-9 Ns
),
.Cm windows-1252
(alias
.Cm cp1252 Ns
) and
.Cm UTF-8
(default).
Case is ignored.
.It Fl f Ns Oo Cm no- Oc Ns Cm show-column
Show the column number in diagnostic messages.
.It Fl fsigned-char
Define
.Sq char
to have the same range, representation and behaviour as
.Sq signed char .
.It Fl funsigned-char
Define
.Sq char
to have the same range, representation and behaviour as
.Sq unsigned char .
.It Fl b Ar option
Set a backend option.
Use
.Fl bhelp
to get a list of supported options.
.It Fl l Ar library
Link with the specified library.
.It Fl o Ar outfile
Specify the output filename.
This is only valid when using a single input filename.
.Fl
as filename uses stdout for output.
.It Fl x Ar language
Overwrite the language auto-detection for the following filenames by the
specified
.Ar language .
Supported values are:
.Bl -tag -compact -width "assembler-with-cpp"
.It Cm assembler
Assembler file
.It Cm assembler-with-cpp
Assembler file, which needs to be preprocessed
.It Cm c
.It Cm c-header
C file
.It Cm c++
.It Cm c++-header
C++ file
.It Cm none
Revert to auto-detection
.El
.It Fl Wl, Ns Ar option
Pass
.Ar option
to the linker.
.It Fl Wp, Ns Ar option
Pass
.Ar option
to the preprocessor.
.El
.Sh SEE ALSO
.Xr gcc 1 ,
http://www.libfirm.org/
.Sh BUGS
Probably many - if you hit one, please report it.
.Pp
.Nm
needs to support more switches for better GCC compatibility.
.Pp
This manual page is incomplete.
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Matthias Braun
.Aq matze@braunis.de ,
.An Christoph Mallon
.Aq christoph.mallon@gmx.de
and
.An Michael Beck .
