#ifndef TARGET_ARCHITECTURE_H
#define TARGET_ARCHITECTURE_H

#include <limits.h>

#define TARGET_INT_MIN     INT_MIN
#define TARGET_INT_MAX     INT_MAX
#define TARGET_UINT_MAX    UINT_MAX

#define TARGET_LONG_MIN    LONG_MIN
#define TARGET_LONG_MAX    LONG_MAX
#define TARGET_ULONG_MAX   ULONG_MAX

#define TARGET_LONGLONG_MIN   LLONG_MIN
#define TARGET_LONGLONG_MAX   LLONG_MAX
#define TARGET_ULONGLONG_MAX  ULLONG_MAX

#endif
